name: CI

on:
  # Run CI on pushes to any branch, but do not run CI on tags.
  push:
    branches:
      - '**'
  # Run CI on all PRs.
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.python-version == 3.6 || matrix.os == 'windows-latest' }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, '3.12']
        exclude:
          # Python version too old for these platforms.
          - os: macos-latest
            python-version: 3.6
          - os: ubuntu-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.6
          # Python version too new for these platforms.
          - os: ubuntu-20.04
            python-version: '3.12'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
      - name: Run Tests
        run: |
          pytest -s tests/
  create_git_tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python '3.12'
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Fetch all git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Make tag if updated
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          git config user.name "github-actions"
          git config user.email "github-actions@noreply.github.com"
          make tag
